import type {
  HostMessage,
  HostRuntimeState,
  HostSnapshot,
  HostState,
} from '@/composables/hostBridge'
import { vi } from 'vitest'
import wireFixture from '../../../.tmp/reports/bridge-fixtures-v2/bootstrap.json'

// Generated by HostBridgeMessagesTests using the production C# serializer.
const fixture = wireFixture as HostMessage
export const makeHostSnapshot = (patch: HostState = {}): HostSnapshot => {
  const state = structuredClone(fixture.state!)
  state.runtime = {
    ...state.runtime,
    isRunning: true,
    processId: 1,
    runtimeEpoch: 1,
    apiStatus: 'ready',
  }
  for (const [key, value] of Object.entries(patch)) {
    if (key in state.runtime) (state.runtime as Record<string, unknown>)[key] = value
    else (state as unknown as Record<string, unknown>)[key] = value
  }
  const kind = state.runtime.coreType ?? 'mihomo'
  state.profiles[kind] = {
    ...state.profiles[kind],
    apiUrl: state.runtime.apiUrl ?? '',
    secret: state.runtime.secret ?? '',
    secretDecryptionFailed: !!state.runtime.secretDecryptionFailed,
  }
  return state
}
export const bootstrapFixture = () => structuredClone(fixture)
export const startMockHost = async (patch: HostState = {}) => {
  const mock = installHostMock(makeHostSnapshot(patch))
  const bridge = await import('@/composables/hostBridge')
  const boot = bridge.requestHost({ type: 'bootstrap' })
  mock.bootstrap()
  await boot
  mock.post.mockClear()
  return { ...mock, bridge }
}
export const installHostMock = (initial = makeHostSnapshot()) => {
  const listeners = new Set<(event: MessageEvent<HostMessage>) => void>()
  let state = initial
  const emit = (message: HostMessage) => {
    for (const listener of [...listeners])
      listener(new MessageEvent('message', { data: { protocolVersion: 2, ...message } }))
  }
  const post = vi.fn()
  const add = vi.fn((_: string, listener: (event: MessageEvent<HostMessage>) => void) =>
    listeners.add(listener),
  )
  const remove = vi.fn((_: string, listener: (event: MessageEvent<HostMessage>) => void) =>
    listeners.delete(listener),
  )
  Object.defineProperty(window, 'chrome', {
    configurable: true,
    value: { webview: { postMessage: post, addEventListener: add, removeEventListener: remove } },
  })
  return {
    post,
    add,
    remove,
    emit,
    setState(next: HostSnapshot) {
      state = next
      emit({ type: 'state', state })
    },
    runtime(patch: HostRuntimeState) {
      state = { ...state, runtime: { ...state.runtime, ...patch } }
      emit({ type: 'runtimeState', runtimeState: patch })
    },
    bootstrap(
      id = post.mock.calls.findLast(([message]) => message.requestId)?.[0].requestId,
      preferences: unknown = {},
    ) {
      emit({
        type: 'bootstrap',
        requestId: id,
        state,
        preferences: preferences as Record<string, string>,
      })
    },
    ack(
      id = post.mock.calls.findLast(([message]) => message.requestId)?.[0].requestId,
      success = true,
      next = state,
    ) {
      state = next
      emit({
        type: 'commandResult',
        requestId: id,
        state,
        result: {
          status: success ? 'completed' : 'failed',
          code: success ? 'saved' : 'saveFailed',
          saved: success,
        },
      })
    },
  }
}
